#! /usr/bin/env bash

(
    git remote remove gitee 2>/dev/null
    git remote add gitee git@gitee.com:x-bash/x-bash.git
    git pull gitee
) || (
    git remote remove github 2>/dev/null
    git remote add github git@github.com:x-bash/x-bash.github.io.git
    git pull github
)
